*teks yang dimiringkan*
You can also create content with Jupyter Notebooks. This means that you can include
code blocks and their outputs in your book.

## Markdown + notebooks

As it is markdown, you can embed images, HTML, etc into your posts!

![](https://myst-parser.readthedocs.io/en/latest/_static/logo-wide.svg)

You can also $add_{math}$ and

$$
math^{blocks}
$$

or

$$
\begin{aligned}
\mbox{mean} la_{tex} \\ \\
math blocks
\end{aligned}
$$

But make sure you \$Escape \$your \$dollar signs \$you want to keep!

## MyST markdown

MyST markdown works in Jupyter Notebooks as well. For more information about MyST markdown, check
out [the MyST guide in Jupyter Book](https://jupyterbook.org/content/myst.html),
or see [the MyST markdown documentation](https://myst-parser.readthedocs.io/en/latest/).

## Code blocks and outputs

Jupyter Book will also embed your code blocks and output in your book.
For example, here's some sample Matplotlib code:

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# TUGAS 1

In [ ]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
plt.ion()

In [ ]:
import pandas as pd
import numpy as np

In [48]:
# Create dataset from Google Drive
dataset_url = "https://raw.githubusercontent.com/AlifnurFathurrahmanPrasodjo/dataFolder/main/dataMining/penambanganData_minuman.csv"
df = pd.read_csv(dataset_url, index_col='IdKabupaten/Kota')

In [49]:
df

,Kabupaten/Kota,Positif,Sembuh,...,Odp,Pdp,Terakhir Update
IdKabupaten/Kota,,,,,,,
1,Kabupaten Blitar,0,0,...,100,1,26-03-2020
2,Kabupaten Tulungagung,1,0,...,204,18,26-03-2020
3,Kabupaten Trenggalek,1,0,...,50,3,26-03-2020
...,...,...,...,...,...,...,...
8,Kabupaten Gresik,0,0,...,3,9,26-03-2020
9,Kabupaten Jombang,0,0,...,28,3,26-03-2020
10,Kabupaten Sampang,0,0,...,29,0,26-03-2020

In [ ]:
# Show dataset shape
number_of_columns = df.shape[1]

In [ ]:
# Show all columns for dataset
pd.set_option('display.max_columns', number_of_columns)
pd.set_option('display.max_rows', number_of_columns)

In [ ]:
# Show all columns from dataframe
df.columns

Index(['Positif', 'Sembuh', 'Vaksinasi', 'Odp', 'Pdp', 'Terakhir Update'], dtype='object')

### Categorical/Nomimal Features


*   Survived
*   Embarked

In [69]:
df[["Kabupaten/Kota","Positif","Vaksinasi"]].head(5)

                         Kabupaten/Kota  Positif Vaksinasi
IdKabupaten/Kota
1                      Kabupaten Blitar        0         Y
2                 Kabupaten Tulungagung        1         N
3                  Kabupaten Trenggalek        1         Y
4                  Kabupaten Bojonegoro        1         Y
5                   Kabupaten Situbondo        0         Y

### Change Values to 1/0


*   Take all values of 'Embarked' *series*
*   If values is S change to 1
*   If values is C change to 0

In [ ]:
# vaksin code
code_embark_for_cherbourg = "N"
code_embark_for_southampton = "Y"

# binary value
value_of_one = 1
value_of_zero = 0

def change_code_embark_to_biner(vaksinasi):
    return value_of_one if vaksinasi == code_embark_for_southampton else value_of_zero

In [ ]:
# Update all values of 'Vaksinasi' series
df["Vaksinasi"] = df["Vaksinasi"].apply(change_code_embark_to_biner)

In [ ]:
df[["Positif", "Vaksinasi"]].head(5)

                       Positif  Vaksinasi
Kabupaten/Kota
Kabupaten Blitar             0          0
Kabupaten Tulungagung        1          0
Kabupaten Trenggalek         1          0
Kabupaten Bojonegoro         1          0
Kabupaten Situbondo          0          0

In [ ]:
# CONSTAN VARIABLE
DECREMENT_BY_ONE = 1
INCREMENT_BY_ONE = 1

CONTINGENCY_TABLE_VALUE = {
    "q" : (1,1),
    "r" : (1,0),
    "s" : (0,1),
    "t" : (0,0),
}

In [ ]:
def get_series(df, idx, series):
    return df.loc[(idx), series]

In [ ]:
def get_dissimilarity_dataset(df, series_index = [], series = []):
    first_series = get_series(df, series_index[0], series)
    second_series = get_series(df, series_index[1], series)
    dataset = pd.concat([first_series,second_series],axis=1)
    return dataset.T

In [52]:
get_dissimilarity_dataset(df, [1,2], ["Positif", "Vaksinasi"]).T

           1  2
Positif    0  1
Vaksinasi  Y  N

In [53]:
df.loc[0:5, ["Positif", "Vaksinasi"]]

                  Positif Vaksinasi
IdKabupaten/Kota
1                       0         Y
2                       1         N
3                       1         Y
4                       1         Y
5                       0         Y

In [54]:
def count_contingency_value(df, start_index = 0, last_index = 1):

    CONTINGENCY_VALUE = {
        "q" : 0,
        "r" : 0,
        "s" : 0,
        "t" : 0,
    }

    column_range = df.shape[1]

    for column in range(column_range):
        for value in CONTINGENCY_TABLE_VALUE:
            item = list((tuple(df.loc[(start_index):(last_index), df.columns[column]]) == CONTINGENCY_TABLE_VALUE[value], value))
            if item[0] == True:
                if item[1] == "q":
                    CONTINGENCY_VALUE["q"] += 1
                if item[1] == "r":
                    CONTINGENCY_VALUE["r"] += 1
                if item[1] == "s":
                    CONTINGENCY_VALUE["s"] += 1
                if item[1] == "t":
                    CONTINGENCY_VALUE["t"] += 1

    return CONTINGENCY_VALUE

In [55]:
# d(1,2)
df_1_2 = get_dissimilarity_dataset(df, [1,2], ["Positif", "Vaksinasi"])

In [56]:
c_d_1_2 = count_contingency_value(df_1_2, 1, 2)

In [57]:
# d(1,3)
df_1_3 = get_dissimilarity_dataset(df, [1,3], ["Positif", "Vaksinasi"])

In [58]:
c_d_1_3 = count_contingency_value(df_1_3, 1, 3)

In [60]:
# d(1,4)
df_1_4 = get_dissimilarity_dataset(df, [1,4], ["Positif", "Vaksinasi"])

In [61]:
c_df_1_4 = count_contingency_value(df_1_4, 1, 4)

In [62]:
# d(1,5)
df_1_5 = get_dissimilarity_dataset(df, [1,5], ["Positif", "Vaksinasi"])

In [63]:
c_df_1_5 = count_contingency_value(df_1_5, 1, 5)

### Dissimilarity Binary Assymetric Value Formula

$$
\frac{r + s}{q + r + s}\
$$

In [64]:
def measure_dissimilarity_binary_value_assymetric_distance(contingency_value):

    return (contingency_value["r"] + contingency_value["s"]) / (contingency_value["q"] + contingency_value["r"] + contingency_value["s"])

In [65]:
d_1_2 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)
d_1_3 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)
d_1_4 = measure_dissimilarity_binary_value_assymetric_distance(c_d_1_2)

In [66]:
d_1_2

1.0

In [67]:
d_1_3

1.0

In [68]:
d_1_4

1.0

# TUGAS 2